### ISSUE TITLE
Use standard order of  hash and account ID in transactionHash field

### ISSUE THREAD

**Issue by prestwich** [nearprotocol/near-web3-provider#9]
Near CLI uses `accountID:Hash` while we currently have `hash:accountID`

**Comment by emaG3m** [comment]
https://github.com/nearprotocol/near-web3-provider/pull/23

**Comment by emaG3m** [comment]
Reverted based on these notes: https://github.com/nearprotocol/near-web3-provider/pull/26#issue-444183236

**Comment by emaG3m** [comment]
@prestwich, I reopened this. Very similar to the `base58` vs `hex` issue. @barbaraliau was going to take one last look to confirm that switching these around might not be doable because web3 doesn't like it. Draft PR mentioned above addresses this.

**Comment by prestwich** [comment]
Ya, web3 has bizarre requirements. Can we add some friendly convenience methods for the conversions and document where and how they need to be used?

**Comment by barbaraliau** [comment]
@emaG3m have you had a chance to see if we can use the `extensions` module to rewrite the input formatter?

**Comment by emaG3m** [comment]
I'm currently looking into base58 right now and am getting pretty pessimistic on that one, just because the complication isn't worth it. I'll look into this as well

**Comment by emaG3m** [comment]
> @emaG3m have you had a chance to see if we can use the `extensions` module to rewrite the input formatter?

IMHO web3 is a merry-go-round of confusion and misery. I'm going to continue adding to our api the rest of the near methods and come back to this. Maybe since you, @barbaraliau are a little more of a JS connoisseur than I, you may be able to get to the bottom of this more easily. I just can't find the place where web3 is reversing these fields and there's some fancy js happening in places. I have a feeling it might be too baked in to just add a different formatter somewhere, but not sure

**Comment by barbaraliau** [comment]
Ok sounds good. We will add it to the 'nice-to-do' list and if there is time to get to it, then we will. Otherwise, documenting the requirement to convert to hex and exposing those methods for the user will be sufficient. Closing this issue as the `transactionHash` now uses the standard order. Opening a new issue to address the option to use `b58`.

**Comment by emaG3m** [comment]
cool. officially this issue consists of documentation. can get around to that.

**Comment by barbaraliau** [comment]
Adding this task to a documentation issue

**Comment by emaG3m** [comment]
> Ya, web3 has bizarre requirements. Can we add some friendly convenience methods for the conversions and document where and how they need to be used?

@prestwich working on this. For the convenience methods I'm guessing you mean `hex <--> base58`. Did you also mean reversing `accountId:txHash`? If so, checking that the input is in the intended order (e.g. handing in `accountId:txHash` instead of `txHash:accountId`) is a weird check because these two values (bordering on never gonna happen) share a bit of overlap which would fail such a check. But I could put in a util function that just reverses two values separated by a semi-colon.

**Comment by prestwich** [comment]
hex <---> base58 would be great. Don't think we need to do the `:` parsing

**Comment by emaG3m** [comment]
https://github.com/nearprotocol/near-web3-provider/pull/45
